name: unit tests
trigger:
  change
jobs:
  e2e_runnable_ckpt_tests:
    # Merlin - data.aml.verl:v85
    image: hub.byted.org/reckon/data.reckon.mlx.image_5940:36aebfdb72c17e002e016c4594c602c4
    if: ${{ !contains(Event.Change.Title, "WIP") }}
    runs-on:
      cluster: gpu-h20
      docker:
        shared-memory: 1024
    envs:
      LIBHDFS_OPTS: -Dhadoop.root.logger=warn,console
    timeout: 30  # timeout 10min
    retry: 2
    steps:
      - name: check env
        commands:
        - nvidia-smi
      - &step_setup_bvc
        name: setup bvc
        commands:
          - curl -s bvc-cdn.byted.org/non_ttp_tao_deploy.sh | sudo bash
          - sudo ln -sf /usr/local/tao/agent/modules/bvc/bin/bvc /usr/bin/bvc
          - mkdir -p /opt/tiger/bvc/bin/; ln -sf /usr/local/tao/agent/modules/bvc/bin/bvc /opt/tiger/bvc/bin/bvc
      - &step_hadoop
        name: setup hadoop
        commands:
          - bash ./tests/tools/setup_hdfs.sh
      - &step_doas
        name: setup doas
        id: doas
        uses: actions/doas
      - &step_dependency
        name: setup dependency
        commands:
          - cd /opt/tiger
          - git clone -b 20250103 git@code.byted.org:seed/seed_models.git
          - cd seed_models
          - pip3 install -e . --user
          - cd /opt/tiger
          - git clone git@code.byted.org:data/verl
          - cd verl
          - pip3 install -e . --user
          - pip3 install bytedance.ndtimeline --upgrade
          - pip3 install byted-omnistore==0.7.11
          - pip3 install pylatexenc

      - name: m8 ckpt save resume omnistore
        commands:
          - cd -
          - export TEST_NAME=ckpt_save_resume
          - export NUM_STEPS=3
          - export N_GPUS_PER_NODE=8
          - export NCCL_SHM_DISABLE=1
          - export SAVE_FREQ=2
          - export CKPT_VERSION=omnistore
          - wandb offline
          - ray stop --force
          - ray start --num-cpus=100 --head
          - bash tasks_scripts/ci/run_m8_100m_math_v1_grpo_ckpt_save_resume.sh
          - export RESUME_STEPS=auto
          - bash tasks_scripts/ci/run_m8_100m_math_v1_grpo_ckpt_save_resume.sh
          - ray stop --force
