name: unit tests
trigger:
  change
jobs:
  e2e_runnable_tests_2:
    # Merlin - data.aml.verl:v205 
    image: hub.byted.org/reckon/data.reckon.mlx.image_5940:26def500fbbd577bdfd57f100f6aa993
    if: ${{ !contains(Event.Change.Title, "WIP") }}
    runs-on:
      cluster: NVIDIA_L20_16|hub.byted.org/reckon/data.reckon.mlx.image_5940:26def500fbbd577bdfd57f100f6aa993
    envs:
      LIBHDFS_OPTS: -Dhadoop.root.logger=warn,console
      SEC_TOKEN_PATH: ${{SEC_TOKEN_PATH}}
      CI_DEBUG_ENABLE: 1
    timeout: 30
    retry: 2
    steps:
      - name: check env
        commands:
          - nvidia-smi

      - name: setup dependency
        commands:
          - cd /opt/tiger
          - git clone -b 20250103 git@code.byted.org:seed/seed_models.git
          - cd /opt/tiger
          - git clone git@code.byted.org:seed/mono_rl.git
          - sudo pip3 install --upgrade byted-wandb
          - sudo pip3 install bytedance.ndtimeline --upgrade
          - sudo pip3 install byted-omnistore==0.7.14
          - sudo pip3 install pylatexenc
          - sudo pip3 install openai
          - sudo pip3 install pydantic==1.10.15
          - sudo pip3 install bytedloadbalance==0.0.14a9
          - sudo pip3 install bytedagi==0.0.37a7

      - name: math v1 ppo async and grpo
        commands:
          - cd /home/code
          - export NUM_STEPS=4
          - export N_GPUS_PER_NODE=8
          - export NCCL_SHM_DISABLE=1
          - export ALPHASEED_USE_NDTIMELINE=1
          - export PYTHONPATH=/opt/tiger/mono_rl:$PYTHONPATH:/opt/tiger/seed_models
          - wandb offline
          - ray stop --force
          - ray start --num-cpus=100 --head
          - bash tasks_scripts/ci/run_p6d_0b5_math_v1_ppo_async.sh
          - bash tasks_scripts/ci/run_p6d_0b5_math_v1_ppo_async_server.sh
          - ray stop --force
