name: unit tests
trigger:
  change
jobs:
  gen_ut:
    image: hub.byted.org/reckon/data.reckon.mlx.image_5940:26def500fbbd577bdfd57f100f6aa993
    if: ${{ !contains(Event.Change.Title, "WIP") }}
    runs-on:
      cluster: NVIDIA_L20_16|hub.byted.org/reckon/data.reckon.mlx.image_5940:26def500fbbd577bdfd57f100f6aa993
    envs:
      LIBHDFS_OPTS: -Dhadoop.root.logger=warn,console
      SEC_TOKEN_PATH: ${{SEC_TOKEN_PATH}}
    timeout: 60
    retry: 2
    steps:
      - name: check env
        commands:
          - nvidia-smi

      - name: setup dependency
        commands:
          - cd /opt/tiger
          - git clone -b v1.3.0 --single-branch git@code.byted.org:seed/seed_models.git
          - git clone git@code.byted.org:seed/mono_rl.git
          - sudo pip3 install --upgrade byted-wandb
          - sudo pip3 install --upgrade bytedance.ndtimeline
          - sudo pip3 install byted-omnistore==0.7.14
          - sudo pip3 install pylatexenc
          - sudo pip3 install openai
          - sudo pip3 install pytest-xdist pytest-timeout

      - name: agents
        commands:
          - export NCCL_SHM_DISABLE=1
          - export PYTHONPATH=$PYTHONPATH:/opt/tiger/mono_rl:/opt/tiger/seed_models
          - export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
          - cd /home/code
          - pytest -n 4 -v tests/agents/test_example_env.py tests/agents/test_example_plugin.py tests/agents/test_query_plugin.py tests/agents/test_plugin_manager.py tests/agents/test_tag_matcher.py
          - ray stop --force
          - ray start --num-cpus=100 --head
          - pytest -n 4 -v -x --timeout=600 tests/agents/test_e2e_gen.py tests/agents/test_call_server_in_rollout_actor.py tests/agents/test_reward_plugin.py
          - ray stop --force

      - name: rollout
        commands:
          - export NCCL_SHM_DISABLE=1
          - export PYTHONPATH=$PYTHONPATH:/opt/tiger/mono_rl:/opt/tiger/seed_models
          - export PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True
          - cd /home/code
          - pytest -n 4 -v tests/rollout/test_cache_manager.py
          - ray stop --force
          - ray start --num-cpus=100 --head
          - |
            pytest -n 2 -v --timeout=600 tests/rollout/test_rollout_manager.py
            pytest -n 2 -v --timeout=600 tests/rollout/test_elastic_rollout.py
          - ray stop --force
