name: unit tests
trigger:
  change
jobs:
  gen_ut:
    image: hub.byted.org/reckon/data.reckon.mlx.image_5940:2f550abbef6349f1fd520d7dbd4fcc1e
    if: ${{ !contains(Event.Change.Title, "WIP") }}
    runs-on:
      cluster: gpu-l20-16
      docker:
        shared-memory: 1024
    envs:
      LIBHDFS_OPTS: -Dhadoop.root.logger=warn,console
    timeout: 30  # timeout 10min
    retry: 2
    steps:
      - name: check env
        commands:
        - nvidia-smi
      - &step_setup_bvc
        name: setup bvc
        commands:
          - curl -s bvc-cdn.byted.org/non_ttp_tao_deploy.sh | sudo bash
          - sudo ln -sf /usr/local/tao/agent/modules/bvc/bin/bvc /usr/bin/bvc
          - mkdir -p /opt/tiger/bvc/bin/; ln -sf /usr/local/tao/agent/modules/bvc/bin/bvc /opt/tiger/bvc/bin/bvc
      - &step_hadoop
        name: setup hadoop
        commands:
          - bash ./tests/tools/setup_hdfs.sh
      - &step_doas
        name: setup doas
        id: doas
        uses: actions/doas
      - &step_dependency
        name: setup dependency
        commands:
          - cd /opt/tiger
          - git clone -b v1.3.0 --single-branch git@code.byted.org:seed/seed_models.git
          - cd seed_models
          - pip3 install -e . --user
          - cd /opt/tiger
          - git clone git@code.byted.org:data/verl
          - cd verl
          - pip3 install -e . --user
          - pip3 install --upgrade byted-wandb
          - pip3 install bytedance.ndtimeline --upgrade
          - pip3 install byted-omnistore==0.7.14
          - pip3 install pylatexenc
          - pip3 install openai
          - pip3 install pydantic==1.10.15
          - pip3 install pytest-xdist
      - name: agents
        commands:
          - export NCCL_SHM_DISABLE=1
          - cd -
          - pytest -n 4 -v tests/agents/test_example_env.py tests/agents/test_example_plugin.py tests/agents/test_query_plugin.py tests/agents/test_plugin_manager.py
          - ray stop --force
          - ray start --num-cpus=100 --head
          - pytest -n 4 -v tests/agents/test_e2e_gen.py
          - ray stop --force
      - name: rollout
        commands:
          - export NCCL_SHM_DISABLE=1
          - cd -
          - pytest -n 4 -v tests/rollout/test_cache_manager.py
          - ray stop --force
          - ray start --num-cpus=100 --head
          - pytest -n 4 -v tests/rollout/test_rollout_manager.py
          - ray stop --force
