name: unit tests
trigger:
  change
jobs:
  model_tests:
    # Merlin - data.aml.verl:v144
    image: hub.byted.org/reckon/data.reckon.mlx.image_5940:36aebfdb72c17e002e016c4594c602c4
    if: ${{ !contains(Event.Change.Title, "WIP") }}
    runs-on:
      cluster: gpu-l20-16
      docker:
        shared-memory: 1024
    envs:
      LIBHDFS_OPTS: -Dhadoop.root.logger=warn,console
    timeout: 10  # timeout 10min
    retry: 3
    steps:
      - name: check env
        commands:
        - nvidia-smi
      - &step_setup_bvc
        name: setup bvc
        commands:
          - curl -s bvc-cdn.byted.org/non_ttp_tao_deploy.sh | sudo bash
          - sudo ln -sf /usr/local/tao/agent/modules/bvc/bin/bvc /usr/bin/bvc
          - mkdir -p /opt/tiger/bvc/bin/; ln -sf /usr/local/tao/agent/modules/bvc/bin/bvc /opt/tiger/bvc/bin/bvc
      - &step_hadoop
        name: setup hadoop
        commands:
          - bash ./tests/tools/setup_hdfs.sh
      - &step_doas
        name: setup doas
        id: doas
        uses: actions/doas
      - &step_setup_env
        name: setup env
        commands:
          - pip3 install --upgrade byted-omnistore
          - pip3 install --upgrade bytedance.ndtimeline
          - cd /opt/tiger
          - git clone git@code.byted.org:data/verl
          - git clone git@code.byted.org:seed/seed_models
          - export PYTHONPATH=/opt/tiger/seed_models:/opt/tiger/verl/:$PYTHONPATH
          - cd -
      - name: monkey patch tests
        commands:
          - pytest -s tests/models/transformers/test_ce_loss_op.py
      - name: parallelize tests
        commands:
          - export export NCCL_SHM_DISABLE=1
          - export PYTHONPATH=/opt/tiger/seed_models:/opt/tiger/verl/:$PYTHONPATH
          - pytest tests/parallelize/test_create_mesh.py
          - pytest tests/parallelize/test_parallel_init.py
          - pytest tests/parallelize/test_group_gemm_ep.py
          - pytest tests/parallelize/test_save_load.py
          - pytest tests/parallelize/test_train_memory_offload.py
          - pytest tests/parallelize/test_omnistore_reshard.py