set -x

NUM_STEPS="${NUM_STEPS:-2000}"
echo $NUM_STEPS

NCCL_DEBUG=WARN

N_GPUS_PER_NODE="${N_GPUS_PER_NODE:-8}"

# ckpt和路径
SFT_MODEL_PATH=hdfs://haruna/home/byte_data_seed/ssd_hldy/user/sunhe/model/qwen3_0.6b_p6d
RM_MODEL_PATH=hdfs://haruna/home/byte_data_seed/ssd_hldy/user/sunhe/model/p6dense-0.5B-Instruct_rm
TRAIN_FILE=hdfs://haruna/home/byte_data_seed/ssd_hldy/user/sunhe/alphaseed_workspace/data/agent/trae/valid_sft_bon_mid_ds3_2197_merged.parquet
TEST_FILE=hdfs://harunawl/home/byte_data_seed_wl/user/jiangyun.jy/datasets/rl_data/openhands_swe_bench_verified_500.parquet
default_hdfs_dir=hdfs://haruna/home/byte_data_seed/lf_lq/user/sunhe/test/p6dense_0b5_agentbench

# 训练长度
max_prompt_length=16384
max_response_length=49152
# batch size && 训练epoch
train_batch_size=32
ppo_mini_batch_size=32
val_batch_size=32
total_epochs=50000
test_freq=100000000
save_freq=-1
# 算法相关的参数
actor_lr=1e-6
critic_lr=2e-6
lr_warmup_steps=0
critic_warmup=0
kl_coef=0.000000001
use_last_response=False
use_ref_answer=True
gae_gamma=1.0
gae_lam=0.95
force_append_eos=True
upgo_loss_weight=0.0
upgo_loss_version=1
clip_ratio_low=0.2
clip_ratio_high=0.2
clip_ratio2=2.0
loss_average_method=token
weight_decay=0.1
adv_estimator=gae
kl_loss_weight=0.00
num_bon=1
bon_strategy=all
kl_penalty=low_var_kl

# tracking实验名
project_name='verl_example_agentless'
experiment_name='ref0825'
# 工程参数
gen_micro_batch_size=32 # use_dynamic_bsz=True时仍然生效
infer_micro_batch_size=32 # use_dynamic_bsz=True时不生效
train_micro_batch_size=32 # use_dynamic_bsz=True时不生效
use_dynamic_bsz=True
actor_ppo_max_token_len=36864
critic_ppo_max_token_len=36864
infer_ppo_max_token_len=36864
actor_sp_size=2
critic_sp_size=2
ref_sp_size=1
reward_sp_size=1
fsdp_size=8
xperf_tp_size=2
offload_train_memory=True

offload=False

python3 tasks/main_ppo.py \
    rollout_server.handler=agent/agentbench \
    algorithm.use_variable_lambda=True \
    algorithm.variable_lambda_scalar=0.05 \
    actor_rollout_ref.actor.loss_average_method='token' \
    algorithm.use_separate_critic_lam=True \
    actor_rollout_ref.ref.ema=0.8 \
    actor_rollout_ref.actor.use_ewma_loss=True \
    algorithm.critic_lam=1.0 \
    critic.ppo_epochs=1 \
    data.return_raw_chat=True \
    data.train_files=${TRAIN_FILE} \
    data.val_files=${TEST_FILE} \
    data.prompt_key=prompt \
    data.answer_key=answer \
    data.use_ref_answer=${use_ref_answer} \
    data.max_prompt_length=${max_prompt_length} \
    data.max_response_length=${max_response_length} \
    data.train_batch_size=${train_batch_size} \
    data.val_batch_size=${val_batch_size} \
    data.truncation='left' \
    +data.chat_template=seed \
    actor_rollout_ref.actor.use_dynamic_bsz=${use_dynamic_bsz} \
    actor_rollout_ref.ref.use_dynamic_bsz=${use_dynamic_bsz} \
    actor_rollout_ref.rollout.use_dynamic_bsz=${use_dynamic_bsz} \
    actor_rollout_ref.actor.ppo_max_token_len=${actor_ppo_max_token_len} \
    actor_rollout_ref.ref.max_token_len=${infer_ppo_max_token_len} \
    actor_rollout_ref.rollout.max_token_len=${infer_ppo_max_token_len} \
    actor_rollout_ref.actor.kl_loss_weight=${kl_loss_weight} \
    actor_rollout_ref.rollout.num_bon=${num_bon} \
    +actor_rollout_ref.rollout.complete_ratio=0 \
    actor_rollout_ref.rollout.bon_strategy=${bon_strategy} \
    +actor_rollout_ref.rollout.drop_truncated=True \
    actor_rollout_ref.actor.shuffle=False \
    actor_rollout_ref.model.path=${SFT_MODEL_PATH} \
    +actor_rollout_ref.model.use_rmpad=True \
    actor_rollout_ref.model.external_lib=seed_models \
    +actor_rollout_ref.model.override_config.attention_dropout=0. \
    +actor_rollout_ref.model.override_config.embd_pdrop=0. \
    +actor_rollout_ref.model.override_config.resid_pdrop=0. \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.optim.lr=${actor_lr} \
    actor_rollout_ref.actor.optim.lr_warmup_steps=${lr_warmup_steps} \
    actor_rollout_ref.actor.ppo_mini_batch_size=${ppo_mini_batch_size} \
    actor_rollout_ref.actor.ppo_micro_batch_size=${train_micro_batch_size} \
    actor_rollout_ref.actor.entropy_coeff=0.0 \
    actor_rollout_ref.actor.clip_ratio_low=${clip_ratio_low} \
    actor_rollout_ref.actor.clip_ratio_high=${clip_ratio_high} \
    actor_rollout_ref.actor.clip_ratio2=${clip_ratio2} \
    actor_rollout_ref.rollout.micro_batch_size=${gen_micro_batch_size} \
    actor_rollout_ref.rollout.tensor_model_parallel_size=${xperf_tp_size} \
    actor_rollout_ref.rollout.name=xperf_gpt \
    +rollout_server.wait_for_task_timeout=14400 \
    +rollout_server.wait_for_request_timeout=3600 \
    +rollout_server.retry=3 \
    actor_rollout_ref.rollout.mode=server \
    +actor_rollout_ref.rollout.use_vllm=True \
    +actor_rollout_ref.rollout.num_slots=256 \
    +actor_rollout_ref.rollout.slot_block_size=1024 \
    trainer.queued_rollout_config.enable=True \
    trainer.queued_rollout_config.chunk_size=4 \
    trainer.queued_rollout_config.concurrency=128 \
    trainer.queued_rollout_config.wait_condition=pool_ready_count \
    trainer.offload_train_memory=${offload_train_memory} \
    actor_rollout_ref.actor.scale_pg_by_kl=False \
    actor_rollout_ref.actor.upgo_loss_weight=${upgo_loss_weight} \
    actor_rollout_ref.actor.upgo_loss_version=${upgo_loss_version} \
    actor_rollout_ref.actor.optim.weight_decay=${weight_decay} \
    actor_rollout_ref.actor.fsdp_size=${fsdp_size} \
    critic.use_dynamic_bsz=${use_dynamic_bsz} \
    critic.ppo_max_token_len=${critic_ppo_max_token_len} \
    critic.optim.lr=${critic_lr} \
    critic.optim.lr_warmup_steps=${lr_warmup_steps} \
    critic.model.path=${RM_MODEL_PATH} \
    critic.model.enable_gradient_checkpointing=True \
    critic.ppo_micro_batch_size=${train_micro_batch_size} \
    critic.infer_micro_batch_size=${infer_micro_batch_size} \
    +critic.model.override_config.attention_dropout=0. \
    +critic.model.override_config.embd_pdrop=0. \
    +critic.model.override_config.resid_pdrop=0. \
    +critic.model.override_config.architectures=['P6DenseForTokenClassification'] \
    +critic.use_rmpad=True \
    critic.model.external_lib=seed_models \
    reward_model.enable=False \
    reward_model.model.input_tokenizer=null \
    reward_model.model.path=${RM_MODEL_PATH} \
    reward_model.micro_batch_size=${infer_micro_batch_size} \
    reward_model.mean=0.0 \
    reward_model.std=1.0 \
    reward_model.use_last_response=${use_last_response} \
    +reward_model.use_rmpad=True \
    reward_model.reward_0_for_overlong_rsp=False \
    reward_model.punish_no_answer=v0 \
    reward_model.add_int_verify=True \
    algorithm.adv_estimator=${adv_estimator} \
    algorithm.kl_ctrl.kl_coef=${kl_coef} \
    algorithm.gamma=${gae_gamma} \
    algorithm.lam=${gae_lam} \
    algorithm.force_append_eos=${force_append_eos} \
    algorithm.kl_penalty=${kl_penalty} \
    algorithm.use_model_output_mask=True \
    critic.use_model_output_mask=True \
    actor_rollout_ref.actor.use_model_output_mask=True \
    trainer.critic_warmup=${critic_warmup} \
    trainer.logger=['console','tracking'] \
    trainer.project_name=${project_name} \
    trainer.experiment_name=${experiment_name} \
    trainer.n_gpus_per_node=${N_GPUS_PER_NODE} \
    trainer.nnodes=1 \
    trainer.donot_resume_data=True \
    trainer.save_cases_to_hdfs=False \
    trainer.save_freq=${save_freq} \
    actor_rollout_ref.rollout.rollout_pool.warmup_step=0 \
    trainer.test_freq=${test_freq} \
    trainer.total_epochs=${total_epochs} \
    trainer.total_steps=${NUM_STEPS} \
    trainer.eval_before_training=False \
    trainer.val_only=False \
    trainer.val_epoch=1 \
    trainer.need_log=False \
    trainer.log_file=/opt/tiger/alpha-seed/log.jsonl \
    trainer.resume_steps="disable" \
    trainer.default_hdfs_dir=${default_hdfs_dir} \
    rollout_server.agent.executor_class='LocalExecutor' \
    rollout_server.agent.max_workers=8 \
    rollout_server.agent.worker_max_concurrency=32 \
    actor_rollout_ref.ref.fsdp_size=${fsdp_size} \
    critic.fsdp_size=${fsdp_size} \
    reward_model.fsdp_size=${fsdp_size} \
    actor_rollout_ref.actor.ulysses_sequence_parallel_size=${actor_sp_size} \
    actor_rollout_ref.ref.ulysses_sequence_parallel_size=${ref_sp_size} \
    critic.ulysses_sequence_parallel_size=${critic_sp_size} \
    reward_model.ulysses_sequence_parallel_size=${reward_sp_size} \
    actor_rollout_ref.rollout.log_prob_micro_batch_size=${infer_micro_batch_size} \
    actor_rollout_ref.ref.log_prob_micro_batch_size=${infer_micro_batch_size} \
    critic.profile.enable=False \
    critic.profile.upload_to_mlx=True \
    critic.profile.filename=actor.tp${xperf_tp_size}.fsdp${fsdp_size} \
    actor_rollout_ref.actor.profile.enable=False \
    actor_rollout_ref.actor.profile.upload_to_mlx=True \
    actor_rollout_ref.actor.profile.filename=actor.tp${xperf_tp_size}.fsdp${fsdp_size} \
    +trainer.agent_max_iterations=50 \
    +trainer.agent_keep_removed_thinking_content=True \
    +trainer.split_conversation_turn_in_train=False \
    +data.agent_rollout_max_new_tokens_in_turn=8192 \
    +data.agent_rollout_max_lengths_in_turn=73728 \
    +data.agent_rollout_eval_max_new_tokens_in_turn=8192 \
    +data.agent_rollout_eval_max_lengths_in_turn=131072 \
    +trainer.agent_fornax_ak="305c49b358bc4d308edd7c7b9d13ccfd" \
    +trainer.agent_fornax_sk="2debd8156b1b4ad08be69c2cdab81f0b" \
    +trainer.overlong_early_stop=True \
    +trainer.swalm_prompt_overlong_train_stratagy="learn_all" \
    +trainer.swalm_response_overlong_train_stratagy="learn_all" \
    +trainer.swalm_max_turn_train_stratagy="learn_all" \
    +data.enable_swalm_agent=True \
    +data.rollout_fillin_bon_rate=0.75 \
    +data.process_stats_strategy="swalm" \
    2>&1 | tee log.txt
