# Configs that should match between server and client, 
# client must provide these configs for calling server
data:
  max_prompt_length: 512
  max_response_length: 512

actor_rollout_ref:
  hybrid_engine: True
  model:
    path: hdfs://haruna/home/byte_data_seed/lf_lq/user/zhangchi.usc1992/models/deepseek-llm-7b-chat
    external_lib: null
    override_config: {}

critic:
  model:
    path: hdfs://haruna/home/byte_data_seed/lf_lq/user/zhangchi.usc1992/models/deepseek-llm-7b-chat
    tokenizer_path: ${actor_rollout_ref.model.path}
    external_lib: ${actor_rollout_ref.model.external_lib}
    override_config: {}

reward_model:
  enable: False
  model:
    input_tokenizer: ${actor_rollout_ref.model.path}  # set this to null if the chat template is identical
    path: hdfs://haruna/home/byte_data_seed/lf_lq/user/zhangchi.usc1992/models/FsfairX-LLaMA3-RM-v0.1
    external_lib: ${actor_rollout_ref.model.external_lib}
  max_prompt_length: ${data.max_prompt_length}
  max_response_length: ${data.max_response_length}
