# Configs that used for server and cannot be overwrited by client config
data:
  max_prompt_length: 512
  max_response_length: 512

actor_rollout_ref:
  hybrid_engine: True
  model:
    path: hdfs://haruna/home/byte_data_seed/lf_lq/user/zhangchi.usc1992/models/deepseek-llm-7b-chat
    external_lib: null
    override_config: {}
  actor:
    strategy: fsdp  # This is for backward-compatibility
    ulysses_sequence_parallel_size: 1
    fsdp_size: -1
    use_dynamic_bsz: True
    ppo_max_token_len: -1
    act_offload: False
    fsdp_config:
      wrap_policy:
        # transformer_layer_cls_to_wrap: None
        min_num_params: 0
      param_offload: False
      use_orig_params: True
  ref:
    fsdp_config:
      param_offload: True
      wrap_policy:
        # transformer_layer_cls_to_wrap: None
        min_num_params: 0
    ulysses_sequence_parallel_size: 1
    fsdp_size: -1
    use_dynamic_bsz: True
    max_token_len: -1
  rollout:
    name: xperf_gpt
    prompt_length: ${data.max_prompt_length}  # for xperf_gpt
    response_length: ${data.max_response_length}

    # for vllm rollout
    dtype: bfloat16 # should align with FSDP
    enforce_eager: True
    free_cache_engine: True
    load_format: dummy_dtensor
    tensor_model_parallel_size: 2
    max_num_batched_tokens: 8192
    max_num_seqs: 1024
    use_dynamic_bsz: True
    max_token_len: -1
    # for xperf_gpt
    quant_mode: "NO_QUANT"
    gpu_memory_utilization: 0.7
  use_cuda_timer: False # doesn't take effect; only for backward-compatibility

critic:
  strategy: fsdp
  model:
    path: hdfs://haruna/home/byte_data_seed/lf_lq/user/zhangchi.usc1992/models/deepseek-llm-7b-chat
    tokenizer_path: ${actor_rollout_ref.model.path}
    override_config: {}
    external_lib: ${actor_rollout_ref.model.external_lib}
    fsdp_config:
      param_offload: False
      wrap_policy:
        # transformer_layer_cls_to_wrap: None
        min_num_params: 0
      use_orig_params: True
  ulysses_sequence_parallel_size: 1
  fsdp_size: -1
  NO_DEVICE_MESH: False # handle old critic ckpt stored as ShardedTensor
  use_dynamic_bsz: True
  ppo_max_token_len: -1
  act_offload: False
  use_cuda_timer: False # doesn't take effect; only for backward-compatibility

reward_model:
  enable: False
  model:
    input_tokenizer: ${actor_rollout_ref.model.path}  # set this to null if the chat template is identical
    path: hdfs://haruna/home/byte_data_seed/lf_lq/user/zhangchi.usc1992/models/FsfairX-LLaMA3-RM-v0.1
    external_lib: ${actor_rollout_ref.model.external_lib}
    fsdp_config:
      min_num_params: 0
      param_offload: True
      use_orig_params: True
  ulysses_sequence_parallel_size: 1
  fsdp_size: -1
  use_dynamic_bsz: True
  max_token_len: -1
  max_length: null
  max_prompt_length: ${data.max_prompt_length}
  max_response_length: ${data.max_response_length}
  reward_executor_maxnum: 128
  use_cuda_timer: False # doesn't take effect; only for backward-compatibility

trainer:
  nnodes: 1
  n_gpus_per_node: 8

streaming_rollout:
  n_gpus_per_node: 0
  nnodes: 0
  warmup_step: 0
  force_eos: False

streaming_validator:
  n_gpus_per_node: 0
  nnodes: 0
