set -x

NUM_STEPS="${NUM_STEPS:-50000}"
echo $NUM_STEPS
ray stop --force
export AGENT_SEARCH_ENGINE=mix
export NCCL_DEBUG=warn
EXP="Seed_9B_Search__64k_baseline"

# ckpt和路径
SFT_MODEL_PATH=hdfs://haruna/home/byte_data_seed/ssd_wlcb/user/qiying.01/projects/agent/models/9b/9b-agentsft-0803
RM_MODEL_PATH=hdfs://haruna/home/byte_data_seed/ssd_wlcb/user/guohongyi.g/model/0814_Seed_P6D_9B_Search_ValuePretrain/checkpoints/global_step_60/critic/huggingface

TRAIN_FILE=hdfs://haruna/home/byte_data_seed/ssd_hldy/user/yueyu/alphaseed_workspace/data/agent/search_ci_0813_train.parquet
TEST_FILE=hdfs://haruna/home/byte_data_seed/ssd_hldy/user/yueyu/alphaseed_workspace/data/agent/search_ci_0813_eval.parquet

default_hdfs_dir=hdfs://harunawl/home/byte_data_seed_wl/user/liulingjun.godzilla/model/${EXP}

# 训练长度
# max_prompt_length=4096
# max_response_length=61440
max_prompt_length=512
max_response_length=512
# batch size && 训练epoch
train_batch_size=32
ppo_mini_batch_size=8
total_epochs=100
test_freq=100
save_freq=-1
# 算法相关的参数
actor_lr=1e-6
critic_lr=2e-6
lr_warmup_steps=5
kl_coef=0.0
use_last_response=False
use_ref_answer=True
gae_gamma=1.0
gae_lam=0.95
force_append_eos=True
upgo_loss_weight=0.0
upgo_loss_version=1
clip_ratio2=2.0
weight_decay=0.1
adv_estimator=gae
kl_loss_weight=0.00
num_bon=1
bon_strategy=all
kl_penalty=low_var_kl
# tracking实验名
project_name='alpha-seed-agent-debug'
# 工程参数
gen_micro_batch_size=512 # use_dynamic_bsz=True时仍然生效
infer_micro_batch_size=512 # use_dynamic_bsz=True时不生效
train_micro_batch_size=64 # use_dynamic_bsz=True时不生效
use_dynamic_bsz=True
actor_ppo_max_token_len=40000
critic_ppo_max_token_len=61440
infer_ppo_max_token_len=61440
actor_sp_size=1
critic_sp_size=1
ref_sp_size=1
reward_sp_size=1
fsdp_size=-1
xperf_tp_size=2
offload=False
offload_train_memory=True
N_GPUS_PER_NODE=4
N_GPUS_PER_NODE_STREAMING=2

python3 tasks/main_ppo.py \
    rollout_server.agent.ci_mode=stateful \
    actor_rollout_ref.rollout.agent.max_turns=100 \
    algorithm.use_variable_lambda=True \
    algorithm.variable_lambda_scalar=0.05 \
    algorithm.use_separate_critic_lam=True \
    algorithm.critic_lam=1.0 \
    trainer.nnodes=1 \
    trainer.n_gpus_per_node=${N_GPUS_PER_NODE} \
    streaming_rollout.nnodes=1 \
    streaming_rollout.n_gpus_per_node=${N_GPUS_PER_NODE_STREAMING} \
    streaming_validator.n_gpus_per_node=${N_GPUS_PER_NODE_STREAMING} \
    streaming_validator.nnodes=1 \
    rollout_server.tool_call_start_token=\"\<\|FunctionCallBegin\|\>\" \
    rollout_server.tool_call_end_token=\"\<\|FunctionCallEnd\|\>\" \
    trainer.use_remote_sandbox=False \
    trainer.use_remote_verifier=False \
    trainer.use_remote_swe_sandbox=False \
    trainer.aider_service_psm='data.aml.code_sandbox_arnold_celery.service.hl' \
    trainer.code_sandbox_psm='data.aml.code_sandbox_arnold_celery.service.hl' \
    trainer.verifier_service_psm="data.aml.online_verifier_yueyu.service.lq" \
    trainer.gaokao_verifier_service_psm="'data.aml.gaokao_verifier_online.service.lq'" \
    actor_rollout_ref.actor.clip_ratio_high=0.28 \
    actor_rollout_ref.actor.loss_average_method='token' \
    +actor_rollout_ref.rollout.assign_test_reward=True \
    +data.assign_test_reward=True \
    trainer.use_remote_search=True \
    reward_model.strict_box_verify=True \
    algorithm.use_model_output_mask=True \
    data.return_raw_chat=True \
    +data.chat_template=chatml_tool_v4 \
    reward_model.last_characters=300 \
    data.train_files=${TRAIN_FILE} \
    data.val_files=${TEST_FILE} \
    data.prompt_key=prompt \
    data.answer_key=answer \
    data.use_ref_answer=${use_ref_answer} \
    data.max_prompt_length=${max_prompt_length} \
    data.max_response_length=${max_response_length} \
    data.train_batch_size=${train_batch_size} \
    data.truncation='left' \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.7 \
    actor_rollout_ref.actor.use_dynamic_bsz=${use_dynamic_bsz} \
    actor_rollout_ref.ref.use_dynamic_bsz=${use_dynamic_bsz} \
    actor_rollout_ref.rollout.use_dynamic_bsz=${use_dynamic_bsz} \
    actor_rollout_ref.actor.ppo_max_token_len=${actor_ppo_max_token_len} \
    actor_rollout_ref.ref.max_token_len=${infer_ppo_max_token_len} \
    actor_rollout_ref.rollout.max_token_len=${infer_ppo_max_token_len} \
    actor_rollout_ref.model.path=${SFT_MODEL_PATH} \
    +actor_rollout_ref.model.use_rmpad=True \
    actor_rollout_ref.model.external_lib=seed_models \
    +actor_rollout_ref.model.override_config.attention_dropout=0. \
    +actor_rollout_ref.model.override_config.embd_pdrop=0. \
    +actor_rollout_ref.model.override_config.resid_pdrop=0. \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.optim.lr=${actor_lr} \
    actor_rollout_ref.actor.optim.lr_warmup_steps=${lr_warmup_steps} \
    actor_rollout_ref.actor.ppo_mini_batch_size=${ppo_mini_batch_size} \
    actor_rollout_ref.actor.ppo_micro_batch_size=${train_micro_batch_size} \
    actor_rollout_ref.actor.entropy_coeff=0.0 \
    actor_rollout_ref.actor.clip_ratio2=${clip_ratio2} \
    actor_rollout_ref.rollout.name=xperf_gpt \
    +actor_rollout_ref.rollout.num_slots=256 \
    +actor_rollout_ref.rollout.slot_block_size=512 \
    actor_rollout_ref.ref.log_prob_micro_batch_size=${infer_micro_batch_size} \
    actor_rollout_ref.actor.scale_pg_by_kl=False \
    actor_rollout_ref.actor.upgo_loss_weight=${upgo_loss_weight} \
    actor_rollout_ref.actor.upgo_loss_version=${upgo_loss_version} \
    actor_rollout_ref.actor.optim.weight_decay=${weight_decay} \
    actor_rollout_ref.use_cuda_timer=True \
    critic.use_dynamic_bsz=${use_dynamic_bsz} \
    critic.ppo_max_token_len=${critic_ppo_max_token_len} \
    critic.optim.lr=${critic_lr} \
    critic.optim.lr_warmup_steps=${lr_warmup_steps} \
    critic.model.path=${RM_MODEL_PATH} \
    critic.model.enable_gradient_checkpointing=True \
    critic.ppo_micro_batch_size=${train_micro_batch_size} \
    critic.infer_micro_batch_size=${infer_micro_batch_size} \
    +critic.model.override_config.architectures=['M8ForTokenClassification'] \
    +critic.model.override_config.attention_dropout=0. \
    +critic.model.override_config.embd_pdrop=0. \
    +critic.model.override_config.resid_pdrop=0. \
    +critic.use_rmpad=True \
    critic.model.external_lib=seed_models \
    critic.use_cuda_timer=True \
    reward_model.enable=False \
    reward_model.model.input_tokenizer=null \
    reward_model.model.path=${RM_MODEL_PATH} \
    reward_model.micro_batch_size=${infer_micro_batch_size} \
    reward_model.mean=0.0 \
    reward_model.std=1.0 \
    reward_model.use_last_response=${use_last_response} \
    +reward_model.use_rmpad=True \
    reward_model.reward_0_for_overlong_rsp=False \
    reward_model.punish_no_answer=v0 \
    reward_model.use_dynamic_bsz=${use_dynamic_bsz} \
    reward_model.max_token_len=${infer_ppo_max_token_len} \
    reward_model.add_int_verify=False \
    reward_model.use_cuda_timer=True \
    algorithm.adv_estimator=${adv_estimator} \
    algorithm.kl_ctrl.kl_coef=${kl_coef} \
    algorithm.gamma=${gae_gamma} \
    algorithm.lam=${gae_lam} \
    algorithm.force_append_eos=${force_append_eos} \
    algorithm.kl_penalty=${kl_penalty} \
    trainer.critic_warmup=0 \
    trainer.logger=['console','tracking'] \
    trainer.project_name=${project_name} \
    trainer.experiment_name=${EXP} \
    trainer.default_hdfs_dir=${default_hdfs_dir} \
    trainer.save_freq=${save_freq} \
    trainer.test_freq=${test_freq} \
    trainer.total_epochs=${total_epochs} \
    trainer.eval_before_training=False \
    trainer.val_only=False \
    trainer.val_epoch=1 \
    trainer.need_log=False \
    trainer.log_file=/opt/tiger/alpha-seed/log.jsonl \
    trainer.resume_steps="disable" \
    +actor_rollout_ref.rollout.max_off_policy_steps=5 \
    actor_rollout_ref.actor.fsdp_size=${fsdp_size} \
    actor_rollout_ref.ref.fsdp_size=${fsdp_size} \
    critic.fsdp_size=${fsdp_size} \
    reward_model.fsdp_size=${fsdp_size} \
    actor_rollout_ref.actor.fsdp_config.param_offload=${offload} \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    critic.model.fsdp_config.param_offload=${offload} \
    reward_model.model.fsdp_config.param_offload=True \
    actor_rollout_ref.actor.ulysses_sequence_parallel_size=${actor_sp_size} \
    actor_rollout_ref.ref.ulysses_sequence_parallel_size=${ref_sp_size} \
    actor_rollout_ref.actor.kl_loss_weight=${kl_loss_weight} \
    actor_rollout_ref.rollout.num_bon=${num_bon} \
    actor_rollout_ref.rollout.bon_strategy=${bon_strategy} \
    actor_rollout_ref.actor.shuffle=False \
    critic.ulysses_sequence_parallel_size=${critic_sp_size} \
    reward_model.ulysses_sequence_parallel_size=${reward_sp_size} \
    actor_rollout_ref.rollout.tensor_model_parallel_size=${xperf_tp_size} \
    +actor_rollout_ref.rollout.use_vllm=True \
    actor_rollout_ref.rollout.micro_batch_size=${gen_micro_batch_size} \
    actor_rollout_ref.rollout.log_prob_micro_batch_size=${infer_micro_batch_size} \
    trainer.offload_train_memory=${offload_train_memory} \
    critic.profile.enable=False \
    critic.profile.upload_to_mlx=True \
    critic.profile.filename=actor.tp${xperf_tp_size}.fsdp${fsdp_size} \
    actor_rollout_ref.actor.profile.enable=False \
    actor_rollout_ref.actor.profile.upload_to_mlx=True \
    actor_rollout_ref.actor.profile.filename=actor.tp${xperf_tp_size}.fsdp${fsdp_size} \
    trainer.total_steps=${NUM_STEPS} \
    +actor_rollout_ref.rollout.complete_ratio=0.5 \
    actor_rollout_ref.rollout.rollout_pool.warmup_step=0 \
    actor_rollout_ref.rollout.mode=server \
    actor_rollout_ref.rollout.weights_communicator=nccl \
    rollout_server.handler=agent/search_ci \
    trainer.num_cases_to_wandb=256