import json
import logging
import os

import ray

from alpha_seed.utils.reward_score.extra_reward import filter_thinking_part, match_visual_cot_format
from alpha_seed.utils.reward_score.vlm_verifiers.base_verifier import ExtractAnswerFailed, VerifierFailed

logger = logging.getLogger(__file__)


# Note: AlphaSeed uses [-1, +1] for reward scores and -2 for error handling, which is different from SeedRL's [0, 1].
def compute_score(solution_str, ground_truth, code_sandbox_psm: str, volc_ark_key: str, volc_model_name: str,
                  **kwargs) -> float:
    try:
        ref = submit_verifier.remote(solution_str, ground_truth, code_sandbox_psm, volc_ark_key, volc_model_name)
        try:
            score = ray.get(ref, timeout=1500)
        except ray.exceptions.GetTimeoutError:
            # timeout
            score = -2
            logger.warning(
                f"[VLM VERIFIER ERROR] compute_score_client got timeout error, with ground_truth={ground_truth}")
            ray.cancel(ref, force=True, recursive=True)
    except Exception as e:
        # other error
        logger.warning(
            f"[VLM VERIFIER ERROR] compute_score_client got unknown error: {e}, with ground_truth={ground_truth}")
        score = -2
    return score


def compute_score_client(solution_str, ground_truth, code_sandbox_psm: str, volc_ark_key: str, volc_model_name: str,
                         data_uid, config, **kwargs) -> float:
    score = None
    if config.trainer.use_remote_verifier:
        # get the remote client endpoint
        handler = ray.get_actor('remote_client')
        # retrieve the score directly
        score = ray.get(handler.get_results.remote(data_uid))

    if score is None:
        score = compute_score(solution_str, ground_truth, code_sandbox_psm, volc_ark_key, volc_model_name)

    return score


@ray.remote(num_cpus=1)
def submit_verifier(response: str, verifier_feature: str, code_sandbox_psm: str, volc_ark_key: str,
                    volc_model_name: str):
    full_rollout = response

    if not response:
        raise ValueError('Empty response!')
    if not verifier_feature:
        raise ValueError('Empty verifier_feature!')

    feature: dict = json.loads(verifier_feature)
    answer: str = feature.get('answer', '')
    verifier_name: str = feature['verifier_name']

    bos_token = "<[BOS_never_used_51bce0c785ca2f68081bfa7d91973934]>"
    bos_assistant_nl = f'{bos_token}assistant\n'
    bos_user_nl = f'{bos_token}user\n'
    eos_token = "<[EOS_never_used_51bce0c785ca2f68081bfa7d91973934]>"

    assert bos_user_nl not in response, 'Assuming `response` to have only decoding rollout and no input context.'
    assert not response.startswith(bos_assistant_nl), 'Leading `[BOS]assistant` belongs to input context, not rollout.'
    assert not response.endswith(eos_token), 'The ending [EOS] should have been removed by post_process_solution_str.'
    if response.startswith(bos_token):
        print(f'[WARNING] The model seems to be generating [BOS]! {repr(full_rollout)}')
        response = ''

    # Ensure that the last turn is from role="assistant", not from other roles such as role="tool":
    k = response.rfind(bos_token)
    while (k >= 0) and (response[k:k + len(bos_assistant_nl)] != bos_assistant_nl):
        response = response[:k]
        if not response.endswith(eos_token):
            print(f'[WARNING] Missing [EOS] before [BOS]! Is this [BOS] generated by the model? {repr(full_rollout)}')
            response = ''
            break
        response = response[:-len(eos_token)]
        k = response.rfind(bos_token)

    # Verify if it follows the VisualCoT format. Allow the last turn to be FC to support LLM FC data.
    if verifier_name not in ('verifier_vstar', 'verifier_zerobench') and os.getenv("THINK_TEMPLATE", "v2") != "v1":
        # Skip these two for now. May delete this `if` in the future.
        if not match_visual_cot_format(response, verifier_feature=feature, allow_last_turn_fc=True):
            response = ''  # Let it fail.

    verify_full_rollout = feature.get('verify_full_rollout',
                                      False) or (verifier_name in ('visual_cot_verifier', 'auxline_rule_verifier'))
    if not verify_full_rollout:
        # Discard turns related with function calling and keep only the last assistant response:
        k = response.rfind(bos_assistant_nl)
        if k >= 0:
            response = response[k + len(bos_assistant_nl):]
        # Discard the CoT part:
        response, _ = filter_thinking_part(response)

    try:
        if response == '':
            raise ExtractAnswerFailed

        # Notice for pip dependencies:
        #   - Verifier "count/pointing/bbox/countbypoint/mcqa/action_count/temporal_ground" requires: shapely==2.0.6 word2number==1.1
        #   - Verifier "gui" requires: jieba==0.42.1 rouge_chinese==1.0.3
        if verifier_name == 'math':
            from alpha_seed.utils.reward_score.vlm_verifiers.math_verifier import MathVerifier
            result = MathVerifier().verify(response=response, verifier_feature_dict=feature)
        elif verifier_name == 'arena_code_switch_verifier':
            from alpha_seed.utils.reward_score.vlm_verifiers.arena_lang_llm_verifier import LLMArenaLangVerifier
            result = LLMArenaLangVerifier().verify(response=response, verifier_feature_dict=feature)
        elif verifier_name == 'math_verifier_service':
            from alpha_seed.utils.reward_score.vlm_verifiers.math_verifier import ModelBasedMathVerifierVolc
            result = ModelBasedMathVerifierVolc(volc_ark_key=volc_ark_key,
                                                volc_model_name=volc_model_name).verify(response=response,
                                                                                        verifier_feature_dict=feature)
        elif verifier_name == 'stem_verifier_service':
            from alpha_seed.utils.reward_score.vlm_verifiers.stem_verifier import ModelBasedStemVerifierVolc
            result = ModelBasedStemVerifierVolc(volc_ark_key=volc_ark_key,
                                                volc_model_name=volc_model_name).verify(response=response,
                                                                                        verifier_feature_dict=feature)
        elif verifier_name == 'puzzle_verifier_service':
            from alpha_seed.utils.reward_score.vlm_verifiers.puzzle_verifier import ModelBasedPuzzleVerifierVolc
            result = ModelBasedPuzzleVerifierVolc(volc_ark_key=volc_ark_key,
                                                  volc_model_name=volc_model_name).verify(response=response,
                                                                                          verifier_feature_dict=feature)
        elif verifier_name == 'code_sandbox':
            from alpha_seed.utils.reward_score.vlm_verifiers.code_sandbox_verifier import CodeSandboxVerifier
            result = CodeSandboxVerifier(code_sandbox_service_psm=code_sandbox_psm).verify(
                response=response, verifier_feature_dict=feature)
        elif verifier_name == 'boxed_str':
            from alpha_seed.utils.reward_score.vlm_verifiers.string_verifier import BoxStrVerifier
            result = BoxStrVerifier().verify(response=response, verifier_feature_dict=feature)
        elif verifier_name == "count":
            from alpha_seed.utils.reward_score.vlm_verifiers.count_verifier import CountVerifier
            result = CountVerifier().verify(response=response, verifier_feature_dict=feature, delta=0.0)
        elif verifier_name == "pointing":
            from alpha_seed.utils.reward_score.vlm_verifiers.point_verifier import PointVerifier
            result = PointVerifier().verify(response=response, verifier_feature_dict=feature)
        elif verifier_name == "bbox":
            from alpha_seed.utils.reward_score.vlm_verifiers.bbox_verifier import BBoxVerifier
            result = BBoxVerifier().verify(response=response, verifier_feature_dict=feature)
        elif verifier_name == "countbypoint":
            from alpha_seed.utils.reward_score.vlm_verifiers.cotcount_verifier import CoTCountVerifier
            result = CoTCountVerifier().verify(response=response, verifier_feature_dict=feature, delta=0.6)
        elif verifier_name == 'plain_str':
            from alpha_seed.utils.reward_score.vlm_verifiers.string_verifier import PlainStrVerifier
            result = PlainStrVerifier().verify(response=response, verifier_feature_dict=feature)
        elif verifier_name == "findiff":
            from alpha_seed.utils.reward_score.vlm_verifiers.finddiff_verifier import FindDiffVerifier
            result = FindDiffVerifier().verify(response=response, verifier_feature_dict=feature)
        elif verifier_name == "finddiffreflect":
            from alpha_seed.utils.reward_score.vlm_verifiers.finddiff_verifier import FindDiffReflectVerifier
            result = FindDiffReflectVerifier().verify(response=response, verifier_feature_dict=feature)
        elif verifier_name == "maze":
            from alpha_seed.utils.reward_score.vlm_verifiers.maze_verifier import MazeVerifier
            result = MazeVerifier().verify(response=response, verifier_feature_dict=feature)
        elif verifier_name == "matching_game":
            from alpha_seed.utils.reward_score.vlm_verifiers.matching_game_verifier import MatchingGameVerifier
            result = MatchingGameVerifier().verify(response=response, verifier_feature_dict=feature)
        elif verifier_name == "gui":
            from alpha_seed.utils.reward_score.vlm_verifiers.gui_verifier import GUIVerifier
            result = GUIVerifier().verify(response=response, verifier_feature_dict=feature)
        elif verifier_name == "mcqa":
            from alpha_seed.utils.reward_score.vlm_verifiers.mcqa_verifier import MCQAVerifier
            result = MCQAVerifier().verify(response=response, verifier_feature_dict=feature)
        elif verifier_name == "action_count":
            from alpha_seed.utils.reward_score.vlm_verifiers.action_count_verifier import ActionCountVerifier
            result = ActionCountVerifier().verify(response=response, verifier_feature_dict=feature, delta=0.8)
        elif verifier_name == "temporal_ground":
            from alpha_seed.utils.reward_score.vlm_verifiers.temporal_ground_verifier import TemporalGroundVerifier
            result = TemporalGroundVerifier().verify(response=response, verifier_feature_dict=feature)
        elif verifier_name == "critic":
            from alpha_seed.utils.reward_score.vlm_verifiers.critic_verifier_v3 import PointwiseCriticVerifier
            result = PointwiseCriticVerifier().verify(response=response, verifier_feature_dict=feature)
        elif verifier_name == "vlm_grounding_complex":
            from alpha_seed.utils.reward_score.vlm_verifiers.grounding_complex import ModelBasedGroundingComplexVerifierVolc
            result = ModelBasedGroundingComplexVerifierVolc(
                volc_ark_key=volc_ark_key, volc_model_name=volc_model_name).verify(response=response,
                                                                                   verifier_feature_dict=feature)
        elif verifier_name == 'visual_cot_verifier':
            from alpha_seed.utils.reward_score.vlm_verifiers.visual_cot_verifier import VisualCoTVerifier
            result = VisualCoTVerifier().verify(response=response, verifier_feature_dict=feature)
        elif verifier_name == 'visual_cot_verifier_geoguess_combine':
            from alpha_seed.utils.reward_score.vlm_verifiers.visual_cot_verifier_geoguess_combine import VisualCoTVerifier_Geo_Combine
            result = VisualCoTVerifier_Geo_Combine().verify(response=response, verifier_feature_dict=feature)
        elif verifier_name == 'verifier_vstar':
            from alpha_seed.utils.reward_score.vlm_verifiers.validation.vstar_verifier import VstarVerifier
            result = VstarVerifier().verify(response=response, verifier_feature_dict=feature)
        elif verifier_name == 'verifier_zerobench':
            from alpha_seed.utils.reward_score.vlm_verifiers.validation.zerobench_verifier import ZeroBenchVerifier
            result = ZeroBenchVerifier().verify(response=response, verifier_feature_dict=feature)
        elif verifier_name == 'bracket_rule_verifier':
            from alpha_seed.utils.reward_score.vlm_verifiers.bracket_rule_verifier import BracketRuleVerifier
            result = BracketRuleVerifier().verify(response=response, verifier_feature_dict=feature)
        elif verifier_name == 'auxline_rule_verifier':
            from alpha_seed.utils.reward_score.vlm_verifiers.auxline_verifier import AuxlineVerifier
            result = AuxlineVerifier().verify(response=response, verifier_feature_dict=feature)
        elif verifier_name == 'point_rule_verifier':
            from alpha_seed.utils.reward_score.vlm_verifiers.auxline_point_verifier import AuxlinePointVerifier
            result = AuxlinePointVerifier().verify(response=response, verifier_feature_dict=feature)
        elif verifier_name == 'video_shuffle':
            from alpha_seed.utils.reward_score.vlm_verifiers.video_shuffle_verifier import VideoShuffleVerifier
            result = VideoShuffleVerifier().verify(response=response, verifier_feature_dict=feature)
        elif verifier_name == 'video_shuffle_strict':
            from alpha_seed.utils.reward_score.vlm_verifiers.video_shuffle_verifier import VideoShuffleVerifierStrict
            result = VideoShuffleVerifierStrict().verify(response=response, verifier_feature_dict=feature)
        else:
            raise NotImplementedError(f'No verifier named "{verifier_name}".')

        final_score = (result.score * 2) - 1  # Convert [0, 1] (SeedRL) to [-1, +1] (AlphaSeed).
        status = json.dumps(
            {
                'tag': 'verified',
                'pred': result.extracted_answer,
                'answer': answer,
                'verifier_name': verifier_name,
                'score': final_score,
            },
            ensure_ascii=False)
        print(f'[VLM VERIFIER INFO] {status}')
        return final_score

    except ExtractAnswerFailed:
        status = json.dumps(
            {
                'tag': 'parsing_fail',
                'pred': full_rollout,
                'answer': answer,
                'verifier_name': verifier_name,
                # Assign lower scores to ill-formatted answers compared to incorrect but well-formatted answers.
                'score': -1.2
            },
            ensure_ascii=False)
        print(f'[VLM VERIFIER WARNING] {status}')
        return -1.2

    except VerifierFailed as e:
        status = json.dumps(
            {
                'tag': f'verifier service failed: {e}',
                'pred': full_rollout,
                'answer': answer,
                'verifier_name': verifier_name,
                'score': -2.0
            },
            ensure_ascii=False)
        print(f'[VLM VERIFIER ERROR] {status}')
        return -2

    except Exception:
        import sys
        import traceback
        tb = ''.join(traceback.format_exception(*sys.exc_info()))
        status = json.dumps(
            {
                'tag': f'verification error: {tb}',
                'pred': full_rollout,
                'answer': answer,
                'verifier_name': verifier_name,
                'score': -2.0
            },
            ensure_ascii=False)
        print(f'[VLM VERIFIER ERROR] {status}')
        return -2
