BASE_MODEL=/data/pretrain/Qwen/Qwen2.5-3B
DATA_DIR=/data/datasets/countdown
REWARD_FILE=/home/huangbz/verl/verl/utils/reward_score/countdown.py 
REWARD_NAME=compute_score

N_GPUS=4
ROLLOUT_TP_SIZE=4
ROLLOUT_N=4
TOTAL_EPOCHS=15
PROJ_NAME="TinyZero"
MODEL_NAME=$(basename $BASE_MODEL)
DATA_NAME=$(basename $DATA_DIR)
EXPERIMENT_NAME="${DATA_NAME}_grpo_${MODEL_NAME}_n${ROLLOUT_N}_ep${TOTAL_EPOCHS}"

PYTHONUNBUFFERED=1 python3 -m verl.trainer.main_ppo \
 custom_reward_function.path=$REWARD_FILE \
 custom_reward_function.name=$REWARD_NAME \
 algorithm.adv_estimator=grpo \
 data.train_files=$DATA_DIR/train.parquet \
 data.val_files=$DATA_DIR/test.parquet \
 data.train_batch_size=16 \
 data.val_batch_size=1312 \
 data.max_prompt_length=256 \
 data.max_response_length=1024 \
 actor_rollout_ref.model.path=$BASE_MODEL \
 actor_rollout_ref.actor.optim.lr=1e-6 \
 actor_rollout_ref.actor.ppo_mini_batch_size=16 \
 actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=1 \
 actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=2 \
 actor_rollout_ref.rollout.tensor_model_parallel_size=$ROLLOUT_TP_SIZE \
 actor_rollout_ref.rollout.gpu_memory_utilization=0.3 \
 actor_rollout_ref.rollout.n=$ROLLOUT_N \
 actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=2 \
 actor_rollout_ref.actor.fsdp_config.param_offload=False \
 actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
 algorithm.kl_ctrl.kl_coef=0.001 \
 trainer.logger=['wandb'] \
 +trainer.val_before_train=False \
 trainer.default_hdfs_dir=null \
 trainer.n_gpus_per_node=$N_GPUS \
 trainer.nnodes=1 \
 trainer.save_freq=100 \
 trainer.test_freq=100 \
 trainer.project_name=$PROJ_NAME \
 trainer.experiment_name=$EXPERIMENT_NAME \
 trainer.total_epochs=$TOTAL_EPOCHS